export const categories = [
      "Content Idea Generation",
      "Writing Assistance",
      "Grammar and Spell Checking",
      "SEO Optimization",
      "Content Distribution",
      "Social Media Management",
      "Video Editing",
      "Graphic Design",
      "Image Editing",
      "Audio Editing",
      "Content Analytics and Insights",
      "Collaboration Tools",
      "Influencer Marketing",
      "Content Monetization",
      "Content Planning and Scheduling",
      "Study Assistance",
      "Note Taking",
      "Research Tools",
      "Homework Help",
      "Online Tutoring",
      "Language Learning",
      "Test Preparation",
      "Educational Games and Quizzes",
      "Virtual Labs",
      "Plagiarism Detection",
      "Citation Formatting",
      "Group Project Collaboration",
      "Lecture Transcription",
      "Time Management and Productivity Tools",
      "Career Guidance and Internship Opportunities",
      "Code Editors and IDEs",
      "Version Control Systems",
      "Code Collaboration Platforms",
      "Code Review Tools",
      "Testing and Debugging Tools",
      "Continuous Integration/Continuous Deployment (CI/CD) Tools",
      "Documentation Generators",
      "API Development and Testing",
      "Performance Monitoring",
      "Dependency Management",
      "DevOps Automation",
      "Serverless Computing",
      "Cloud Development Platforms",
      "Microservices Architecture",
      "Containerization Tools",
      "Graphic Design Software",
      "Vector Illustration Tools",
      "Photo Editing and Retouching",
      "Typography Tools",
      "Color Palette Generators",
      "UI/UX Design Tools",
      "Wireframing and Prototyping",
      "Motion Graphics Software",
      "3D Modeling and Rendering",
      "Animation Tools",
      "Video Editing Software",
      "Illustration Marketplaces",
      "Design Collaboration Platforms",
      "Asset Management Systems",
      "Presentation Tools"
];

  